### ISSUE TITLE
Maven Dependancy

### ISSUE THREAD

**Issue by djar** [3scale/3scale_ws_api_for_java#20]
Is it possible to install the 3scale lib as a dependancy to my POM file?  something along the lines of 

		<dependency>
			<groupId>net.threescale</groupId>
			<artifactId>threescale-api</artifactId>
			<version>3.0.1</version>
		</dependency>

using a repository tag perhaps?

**Comment by riteshimoonlight** [comment]
Do you guys have the lib (threescale-api) in maven repository? If yes, which repository? I could not find it in maven central. Can you please share the repository and dependency definition for this api?

**Comment by 3scale-support** [comment]
Hi
We don't currently have it deployed there.
We do intend to do this when we can allocate a resource to do so.




Tom Corcoran | Sales Engineering

*3SCALE | Out-of-the-Box API Management Platform*

email: tom@3scale.net
mobile:  +34 671 102 875
web: http://www.3scale.net

**Comment by afiore** [comment]
Any updates on this? Also, when doing this, could you please review and merge #27?

**Comment by EricWittmann** [comment]
This is obviously super late, but I just wanted to update this issue.  This maven project is now available in Central here:

http://repo.maven.apache.org/maven2/net/3scale/3scale-api/3.0.2/

As of 3.0.2 you will notice some changes to the groupId and artifactId.

Also note that https://github.com/3scale/3scale_ws_api_for_java/pull/27 was subsumed (and therefore closed) by https://github.com/3scale/3scale_ws_api_for_java/pull/29
