### ISSUE TITLE
ServerAccessorDriver NullPointerException

### ISSUE THREAD

**Issue by gobblechops** [3scale/3scale_ws_api_for_java#23]
HttpUrlConnection::getInputStream() is not guaranteed to be non-null, and we have seen cases where this is the case.  However, the output of this method is sent into ServerAccessorDriver::getBody(InputStream) without checking whether it is null.  In rare scenarios this is causing NPE to bubble up from the plugin.  Please add a check for this.

**Comment by manrodriguezf** [comment]
Hi @mpguerra ,
This issue is still happening,  there's a missing **catch** clause for another NPE when handling the original IOException, around line 75 in ServerAccessorDriver.java.
Could we also guys to patch version 3.0.2 and above?
Thanks for your help! :smiley:

**Comment by mayorova** [comment]
Fixed by #37
