### ISSUE TITLE
service_token should be supported along with provider_key

### ISSUE THREAD

**Issue by avilatusell** [3scale/3scale_ws_api_for_java#32]
The plugin would need to be updated to support service_token along with provider_key.

**Comment by EricWittmann** [comment]
If you explain what needs to happen (or link to existing documentation that explains the service_token) I'm happy to make the change.

**Comment by EricWittmann** [comment]
https://github.com/3scale/3scale_ws_api_for_ruby/pull/49/

**Comment by unleashed** [comment]
@EricWittmann you basically want to provide an alternate method to call into 3scale's backend - the user story is people don't want to have provider keys, which open all sorts of permissions on an organization's account; they want to have service tokens, which authenticate against single services. So the plugin should accept a service token + service id combination (as well as keep the option of using a provider key + service id for existing users).

**Comment by EricWittmann** [comment]
OK thanks - I'll have a look at the ruby changes and let you know if I have any other questions. :)

**Comment by thomasmaas** [comment]
done in #33
