### ISSUE TITLE
No traffic is authorised when the plugin receives a 504 from 3scale

### ISSUE THREAD

**Issue by kevprice83** [3scale/3scale_ws_api_for_java#34]
Right now if a 504 is returned to the Java gateway it will reject all traffic. There is a code snippet which is shared [here](https://support.3scale.net/codehub/use-prebuilt-cache), this pre-builds a static cache of all the keys and handles the 504 response from 3scale.

It would be nice to implement the same logic in the Java plugin also. The easiest way to pre-build the cache is to use the 3scale APIs to query for this information, parse it and then store it as in the above example.

cc @EricWittmann

**Comment by EricWittmann** [comment]
The supplied code snippet doesn't seem to "pre-build a static cache of all the keys".  Instead, it seems to cache only the keys that it has previously seen.  This is a much easier implementation than fetching ALL the information, parsing it, and pre-building (seeding) the cache.

Or am I mis-understanding the snippet?  :)

**Comment by kevprice83** [comment]
Well, what I mean is the table is pre-populated and this can be done manually or via an API call (which requires extracting the keys you want), ideally this would be done before starting up the gateway so all the existing keys are stored in this whitelist. Imagine the account has thousands of applications, doing this manually would not be an option.

The keys could be stored as the requests come in but this would then rely on all applications having made a real request to the gateway before a 504 response occurs, a corner case I know but better to cover all possibilities. :)

**Comment by MarkCheshire** [comment]
The plugin libraries are designed as wrappers for the Service Management REST API. They are not intended to extend scope to replicate behavior of a full gateway. However if the community wants to take a fork and add caching, we are happy to reference those more advanced options.

**Comment by EricWittmann** [comment]
Sample code can be found here:  https://github.com/EricWittmann/3scale_ws_api_for_java_sample

It's not fantastic but shows an example of how this could be done.
